package app;

import controladores.ConductorControlador;
import controladores.VehiculoControlador;
import controladores.ViajeControlador;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.Ciudad;
import modelo.Conductor;
import modelo.Viaje;
import servicios.CiudadServiceImpl;

public class VentanaViajes extends javax.swing.JInternalFrame {

    private ViajeControlador viajeControlador;
    private ConductorControlador conductorControlador;
    private VehiculoControlador vehiculoControlador;
    private CiudadServiceImpl ciudadService;

    public VentanaViajes(ViajeControlador controlador, ConductorControlador conductorControlador, VehiculoControlador vehiculoControlador, CiudadServiceImpl ciudadService) {
    initComponents();
    this.viajeControlador = controlador;
    this.conductorControlador = conductorControlador;
    this.vehiculoControlador = vehiculoControlador;
    this.ciudadService = ciudadService;
    viajeControlador.setTabla(tablaViajes);
    viajeControlador.setComboBoxes(cbConductor, cbComboVehiculo, cbOrigen, cbDestino);
    viajeControlador.actualizarTabla();
    viajeControlador.actualizarComboBoxes();
}

    private void tablaViajesMouseClicked(MouseEvent evt) {
        int selectedRow = tablaViajes.getSelectedRow();
        if (selectedRow >= 0) {
            String idConductor = tablaViajes.getValueAt(selectedRow, 1).toString();
            String placaVehiculo = tablaViajes.getValueAt(selectedRow, 2).toString();
            String origenNombre = tablaViajes.getValueAt(selectedRow, 3).toString();
            String destinoNombre = tablaViajes.getValueAt(selectedRow, 4).toString();

            List<Conductor> conductores = viajeControlador.getViajeService().getConductorService().listarConductores();
            for (Conductor conductor : conductores) {
                String nombreCompleto = conductor.getNombre() + " " + conductor.getApellido();
                if (conductor.getIdentificacion().equals(idConductor)) {
                    cbConductor.setSelectedItem(nombreCompleto);
                    break;
                }
            }
            cbComboVehiculo.setSelectedItem(placaVehiculo);

            List<Ciudad> ciudades = viajeControlador.getCiudadService().listarCiudades();
            for (Ciudad ciudad : ciudades) {
                if (ciudad.getNombre().equals(origenNombre)) {
                    cbOrigen.setSelectedItem(ciudad);
                }
                if (ciudad.getNombre().equals(destinoNombre)) {
                    cbOrigen.setSelectedItem(ciudad);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnModificarVia = new javax.swing.JButton();
        btnCancelarViaj = new javax.swing.JButton();
        btnInciarViaje1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cbComboVehiculo = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        cbConductor = new javax.swing.JComboBox<>();
        cbOrigen = new javax.swing.JComboBox<>();
        cbDestino = new javax.swing.JComboBox<>();
        btnDetener = new javax.swing.JButton();
        btnArrancar1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btn_logout = new javax.swing.JButton();
        btn_photo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtIdentificacionC3 = new javax.swing.JTextField();
        btnBuscarCon = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaViajes = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 0), 2));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnModificarVia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnModificarVia.setText("Modificar");
        btnModificarVia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarViaActionPerformed(evt);
            }
        });
        jPanel6.add(btnModificarVia, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        btnCancelarViaj.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelarViaj.setText("Cancelar");
        btnCancelarViaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarViajActionPerformed(evt);
            }
        });
        jPanel6.add(btnCancelarViaj, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        btnInciarViaje1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInciarViaje1.setText("Iniciar");
        btnInciarViaje1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInciarViaje1ActionPerformed(evt);
            }
        });
        jPanel6.add(btnInciarViaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, 490, 100));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Seleccionar Conductor");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 200, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Origen");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 58, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Destino");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 80, -1));

        jPanel3.add(cbComboVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 260, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Seleccionar Vehiculo");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 190, -1));

        cbConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbConductorActionPerformed(evt);
            }
        });
        jPanel3.add(cbConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 260, 30));

        cbOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOrigenActionPerformed(evt);
            }
        });
        jPanel3.add(cbOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 260, 30));

        cbDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(cbDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 260, 30));

        btnDetener.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDetener.setText("Detener");
        btnDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetenerActionPerformed(evt);
            }
        });
        jPanel3.add(btnDetener, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, -1));

        btnArrancar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnArrancar1.setText("Arrancar");
        btnArrancar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArrancar1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnArrancar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 510, 470));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255), 3));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_logout.setText("Salir");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jPanel4.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 30, -1, 30));

        btn_photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/man.png"))); // NOI18N
        btn_photo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_photoActionPerformed(evt);
            }
        });
        jPanel4.add(btn_photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 80, 65));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("RAPIDOS Y SEGUROS VIAJES");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 350, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 90));

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 0), 2));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("Conductor");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 110, -1));
        jPanel7.add(txtIdentificacionC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 260, 30));

        btnBuscarCon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarCon.setText("Buscar");
        btnBuscarCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarConActionPerformed(evt);
            }
        });
        jPanel7.add(btnBuscarCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, -1));

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 590, 100));

        tablaViajes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tablaViajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Conductor", "Vehiculo", "Origen", "Destino"
            }
        ));
        jScrollPane3.setViewportView(tablaViajes);

        jPanel5.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 590, 170));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 610, 470));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1150, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1168, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed


    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_photoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_photoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_photoActionPerformed

    private void btnDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetenerActionPerformed
        int selectedRow = tablaViajes.getSelectedRow();
        if (selectedRow >= 0) {
            String id = tablaViajes.getValueAt(selectedRow, 0).toString();
            try {
                viajeControlador.detenerViaje(id);
                JOptionPane.showMessageDialog(this, "Viaje detenido correctamente.");
            } catch (IllegalStateException | IllegalArgumentException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona un viaje para detener.");
        }
    }//GEN-LAST:event_btnDetenerActionPerformed

    private void btnModificarViaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarViaActionPerformed
        int selectedRow = tablaViajes.getSelectedRow();
        if (selectedRow >= 0) {
            String id = tablaViajes.getValueAt(selectedRow, 0).toString();
            String nombreConductor = (String) cbConductor.getSelectedItem();
            String placaVehiculo = (String) cbComboVehiculo.getSelectedItem();

            // Obtener los objetos Ciudad desde los nombres seleccionados
            Ciudad origen = buscarCiudadPorNombre((String) cbOrigen.getSelectedItem());
            Ciudad destino = buscarCiudadPorNombre((String) cbDestino.getSelectedItem());

            if (nombreConductor == null || placaVehiculo == null || origen == null || destino == null) {
                JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.");
                return;
            }

            try {
                viajeControlador.modificarViaje(id, nombreConductor, placaVehiculo, origen, destino);
                JOptionPane.showMessageDialog(this, "Viaje modificado correctamente.");
                limpiarCampos();
            } catch (IllegalArgumentException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona un viaje para modificar.");
        }
    }//GEN-LAST:event_btnModificarViaActionPerformed

    private void btnCancelarViajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarViajActionPerformed
        int selectedRow = tablaViajes.getSelectedRow();
        if (selectedRow >= 0) {
            String id = tablaViajes.getValueAt(selectedRow, 0).toString();
            viajeControlador.eliminarViaje(id);
            JOptionPane.showMessageDialog(this, "Viaje cancelado correctamente.");
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona un viaje para cancelar.");
        }
    }//GEN-LAST:event_btnCancelarViajActionPerformed
    private void limpiarCampos() {
        cbConductor.setSelectedIndex(-1);
        cbComboVehiculo.setSelectedIndex(-1);
        cbOrigen.setSelectedIndex(-1);
        cbDestino.setSelectedIndex(-1);
        tablaViajes.clearSelection();
        viajeControlador.actualizarTabla();
    }

    private void cbConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbConductorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbConductorActionPerformed


    private void btnBuscarConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarConActionPerformed

    }//GEN-LAST:event_btnBuscarConActionPerformed

    private void btnInciarViaje1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInciarViaje1ActionPerformed
        String nombreConductor = (String) cbConductor.getSelectedItem();
        String placaVehiculo = (String) cbComboVehiculo.getSelectedItem();

        // Obtener los objetos Ciudad desde los nombres seleccionados
        Ciudad origen = buscarCiudadPorNombre((String) cbOrigen.getSelectedItem());
        Ciudad destino = buscarCiudadPorNombre((String) cbDestino.getSelectedItem());

        if (nombreConductor == null || placaVehiculo == null || origen == null || destino == null) {
            JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.");
            return;
        }

        try {
            viajeControlador.registrarViaje(nombreConductor, placaVehiculo, origen, destino);
            JOptionPane.showMessageDialog(this, "Viaje iniciado correctamente.");
            limpiarCampos();
        } catch (IllegalStateException | IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnInciarViaje1ActionPerformed

    private void btnArrancar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArrancar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnArrancar1ActionPerformed

    private void cbOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbOrigenActionPerformed

    private Ciudad buscarCiudadPorNombre(String nombre) {
        if (nombre == null) {
            return null;
        }
        List<Ciudad> ciudades = ciudadService.listarCiudades();
        for (Ciudad ciudad : ciudades) {
            if (ciudad.getNombre().equals(nombre)) {
                return ciudad;
            }
        }
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArrancar1;
    private javax.swing.JButton btnBuscarCon;
    private javax.swing.JButton btnCancelarViaj;
    private javax.swing.JButton btnDetener;
    private javax.swing.JButton btnInciarViaje1;
    private javax.swing.JButton btnModificarVia;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_photo;
    private javax.swing.JComboBox<String> cbComboVehiculo;
    private javax.swing.JComboBox<String> cbConductor;
    private javax.swing.JComboBox<String> cbDestino;
    private javax.swing.JComboBox<String> cbOrigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tablaViajes;
    private javax.swing.JTextField txtIdentificacionC3;
    // End of variables declaration//GEN-END:variables
}
