package app;

import Repositorio.ConductorRepository;
import Servicios.ConductorServiceImpl;
import controladores.ConductorControlador;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;

public class VentanaConductor extends javax.swing.JInternalFrame {

    private ConductorControlador conductorControlador;

    public VentanaConductor(ConductorControlador controlador) {
        initComponents();
        this.conductorControlador = controlador;
        conductorControlador.setTabla(tablaConductores);
        conductorControlador.actualizarTabla();
       
    }

    private void tablaConductoresMouseClicked(MouseEvent evt) {
        int selectedRow = tablaConductores.getSelectedRow();
        if (selectedRow >= 0) {
            txtNombreC.setText(tablaConductores.getValueAt(selectedRow, 0).toString());
            txtApellidoC.setText(tablaConductores.getValueAt(selectedRow, 1).toString());
            txtIdentificacionC4.setText(tablaConductores.getValueAt(selectedRow, 2).toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnRegistrarConductor = new javax.swing.JButton();
        btnModificarConductor = new javax.swing.JButton();
        EliminarConductor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreC = new javax.swing.JTextField();
        txtApellidoC = new javax.swing.JTextField();
        txtIdentificacionC4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btn_logout = new javax.swing.JButton();
        btn_photo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnBuscarC = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtBuscadorID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaConductores = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 0), 2));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrarConductor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrarConductor.setText("Registrar");
        btnRegistrarConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarConductorActionPerformed(evt);
            }
        });
        jPanel6.add(btnRegistrarConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        btnModificarConductor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnModificarConductor.setText("Modificar");
        btnModificarConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarConductorActionPerformed(evt);
            }
        });
        jPanel6.add(btnModificarConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        EliminarConductor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EliminarConductor.setText("Elminar");
        EliminarConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarConductorActionPerformed(evt);
            }
        });
        jPanel6.add(EliminarConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, 490, 100));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Nombre");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 80, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Apellido");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 80, -1));

        txtNombreC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCActionPerformed(evt);
            }
        });
        jPanel3.add(txtNombreC, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 260, 30));
        jPanel3.add(txtApellidoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 260, 30));
        jPanel3.add(txtIdentificacionC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 260, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Identificacion");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 120, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 510, 520));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255), 3));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_logout.setText("Salir");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jPanel4.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 30, -1, 30));

        btn_photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/man.png"))); // NOI18N
        btn_photo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_photoActionPerformed(evt);
            }
        });
        jPanel4.add(btn_photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 80, 65));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("RAPIDOS Y SEGUROS VIAJES");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 350, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 90));

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 0), 2));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscarC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarC.setText("Buscar");
        jPanel7.add(btnBuscarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Identificacion");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 130, 20));

        txtBuscadorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscadorIDActionPerformed(evt);
            }
        });
        jPanel7.add(txtBuscadorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 260, 30));

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 620, 100));

        tablaConductores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tablaConductores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Identificacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaConductores);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 620, 200));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 640, 520));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1180, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1215, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed

        if (evt.getSource() == btn_logout) {
            dispose();
            VentanaNueva ventana = new VentanaNueva();
            ventana.setVisible(true);
        }

    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_photoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_photoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_photoActionPerformed

    private void btnRegistrarConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarConductorActionPerformed
        String nombre = txtNombreC.getText().trim();
        String apellido = txtApellidoC.getText().trim();
        String identificacion = txtIdentificacionC4.getText().trim();

        if (!nombre.isEmpty() && !apellido.isEmpty() && !identificacion.isEmpty()) {
            conductorControlador.registrarConductor(nombre, apellido, identificacion);
            conductorControlador.actualizarTabla();
           
            limpiarCampos();
            JOptionPane.showMessageDialog(this, "Conductor registrado correctamente.");
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.");
        }

    }//GEN-LAST:event_btnRegistrarConductorActionPerformed

    private void btnModificarConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarConductorActionPerformed
        int filaSeleccionada = tablaConductores.getSelectedRow();
        if (filaSeleccionada >= 0) {
            String id = tablaConductores.getValueAt(filaSeleccionada, 2).toString();
            String nuevoNombre = txtNombreC.getText().trim();
            String nuevoApellido = txtApellidoC.getText().trim();

            conductorControlador.modificarConductor(id, nuevoNombre, nuevoApellido);
            conductorControlador.actualizarTabla();
            
            limpiarCampos();
            JOptionPane.showMessageDialog(this, "Conductor modificado correctamente.");
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona un conductor para modificar.");
        }

    }//GEN-LAST:event_btnModificarConductorActionPerformed

    private void EliminarConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarConductorActionPerformed
        int filaSeleccionada = tablaConductores.getSelectedRow();
        if (filaSeleccionada >= 0) {
            String id = tablaConductores.getValueAt(filaSeleccionada, 2).toString();
            conductorControlador.eliminarConductor(id);
            conductorControlador.actualizarTabla();
           
            limpiarCampos();
            JOptionPane.showMessageDialog(this, "Conductor eliminado correctamente.");
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona un conductor para eliminar.");
        }
    }//GEN-LAST:event_EliminarConductorActionPerformed

    private void limpiarCampos() {
        txtNombreC.setText("");
        txtApellidoC.setText("");
        txtIdentificacionC4.setText("");
        txtBuscadorID.setText("");
        tablaConductores.clearSelection();
    }

    private void txtBuscadorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscadorIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscadorIDActionPerformed

    private void txtNombreCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EliminarConductor;
    private javax.swing.JButton btnBuscarC;
    private javax.swing.JButton btnModificarConductor;
    private javax.swing.JButton btnRegistrarConductor;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_photo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaConductores;
    private javax.swing.JTextField txtApellidoC;
    private javax.swing.JTextField txtBuscadorID;
    private javax.swing.JTextField txtIdentificacionC4;
    private javax.swing.JTextField txtNombreC;
    // End of variables declaration//GEN-END:variables
}
