package app;

import controladores.ConductorControlador;
import controladores.VehiculoControlador;

import interfaces.VehiculoService;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;

public class VentanaVehiculo extends javax.swing.JInternalFrame {

    private VehiculoControlador vehiculoControlador;
    private ConductorControlador conductorControlador;
    

    public VentanaVehiculo(VehiculoControlador controlador, ConductorControlador conductorControlador) {
        initComponents();
        this.vehiculoControlador = controlador;
        this.conductorControlador = conductorControlador;
        vehiculoControlador.setTabla(tablaVehiculos);
       vehiculoControlador.setComboBoxConductores(cbConductores);
    

        vehiculoControlador.actualizarTabla();
        vehiculoControlador.actualizarComboBox();

    }

    private void tablaVehiculosMouseClicked(MouseEvent evt) {
        int selectedRow = tablaVehiculos.getSelectedRow();
        if (selectedRow >= 0) {
            txtPlaca.setText(tablaVehiculos.getValueAt(selectedRow, 0).toString());
            txtPotencia.setText(tablaVehiculos.getValueAt(selectedRow, 1).toString());
            cbConductores.setSelectedItem(tablaVehiculos.getValueAt(selectedRow, 2));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnRegistrarVehiculo = new javax.swing.JButton();
        btnModificarPa1 = new javax.swing.JButton();
        btn_eliminar_doctor1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPotencia = new javax.swing.JTextField();
        cbConductores = new javax.swing.JComboBox<>();
        txtPlaca = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTipoMotor = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btn_logout = new javax.swing.JButton();
        btn_photo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtIdentificacionC2 = new javax.swing.JTextField();
        btnBuscarP = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaVehiculos = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 0), 2));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrarVehiculo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrarVehiculo.setText("Registrar ");
        btnRegistrarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVehiculoActionPerformed(evt);
            }
        });
        jPanel6.add(btnRegistrarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 100, -1));

        btnModificarPa1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnModificarPa1.setText("Modificar ");
        btnModificarPa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPa1ActionPerformed(evt);
            }
        });
        jPanel6.add(btnModificarPa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 100, -1));

        btn_eliminar_doctor1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_eliminar_doctor1.setText("Eliminar");
        btn_eliminar_doctor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminar_doctor1ActionPerformed(evt);
            }
        });
        jPanel6.add(btn_eliminar_doctor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 90, -1));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, 490, 100));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Placa");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 60, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("TipoMotor");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 100, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Conductor");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 110, 30));
        jPanel3.add(txtPotencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 260, 30));

        cbConductores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbConductoresActionPerformed(evt);
            }
        });
        jPanel3.add(cbConductores, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 260, 30));

        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });
        jPanel3.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 260, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Potencia");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 80, 30));

        txtTipoMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoMotorActionPerformed(evt);
            }
        });
        jPanel3.add(txtTipoMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 260, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 510, 520));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255), 3));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_logout.setText("Salir");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jPanel4.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 30, -1, 30));

        btn_photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/man.png"))); // NOI18N
        btn_photo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_photoActionPerformed(evt);
            }
        });
        jPanel4.add(btn_photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 80, 65));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("RAPIDOS Y SEGUROS VIAJES");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 350, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 90));

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 0), 2));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Placa");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 50, -1));
        jPanel7.add(txtIdentificacionC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 260, 30));

        btnBuscarP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarP.setText("Buscar");
        jPanel7.add(btnBuscarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 620, 100));

        tablaVehiculos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tablaVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Placa", "Potencia", "Motor", "EstadoMotor"
            }
        ));
        jScrollPane2.setViewportView(tablaVehiculos);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 620, 200));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 640, 520));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1180, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1215, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed

        if (evt.getSource() == btn_logout) {
            dispose();
            VentanaNueva ventana = new VentanaNueva();
            ventana.setVisible(true);
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_photoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_photoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_photoActionPerformed

    private void btnRegistrarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVehiculoActionPerformed
        String placa = txtPlaca.getText().trim();
        String potenciaStr = txtPotencia.getText().trim();
        String nombreConductor = (String) cbConductores.getSelectedItem();

        if (placa.isEmpty() || potenciaStr.isEmpty() || nombreConductor == null) {
            JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.");
            return;
        }

        try {
            int potencia = Integer.parseInt(potenciaStr);
            vehiculoControlador.registrarVehiculo(placa, potencia, nombreConductor);
            vehiculoControlador.actualizarTabla();
            limpiarCampos();
            JOptionPane.showMessageDialog(this, "Vehículo registrado correctamente.");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La potencia debe ser un número entero.");
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnRegistrarVehiculoActionPerformed

    private void btnModificarPa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPa1ActionPerformed
        int selectedRow = tablaVehiculos.getSelectedRow();
        if (selectedRow >= 0) {
            String placa = txtPlaca.getText().trim();
            String potenciaStr = txtPotencia.getText().trim();
            String nombreConductor = (String) cbConductores.getSelectedItem();

            if (placa.isEmpty() || potenciaStr.isEmpty() || nombreConductor == null) {
                JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.");
                return;
            }

            try {
                int potencia = Integer.parseInt(potenciaStr);
                vehiculoControlador.modificarVehiculo(placa, potencia, nombreConductor);
                vehiculoControlador.actualizarTabla();
                limpiarCampos();
                JOptionPane.showMessageDialog(this, "Vehículo modificado correctamente.");
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "La potencia debe ser un número entero.");
            } catch (IllegalArgumentException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona un vehículo para modificar.");
        }
    }//GEN-LAST:event_btnModificarPa1ActionPerformed

    private void btn_eliminar_doctor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminar_doctor1ActionPerformed
        int selectedRow = tablaVehiculos.getSelectedRow();
        if (selectedRow >= 0) {
            String placa = (String) tablaVehiculos.getValueAt(selectedRow, 0);
            vehiculoControlador.eliminarVehiculo(placa);
            vehiculoControlador.actualizarTabla();
            limpiarCampos();
            JOptionPane.showMessageDialog(this, "Vehículo eliminado correctamente.");
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona un vehículo para eliminar.");
        }
    }//GEN-LAST:event_btn_eliminar_doctor1ActionPerformed

    private void limpiarCampos() {
        txtPlaca.setText("");
        txtPotencia.setText("");
        cbConductores.setSelectedIndex(0);
        tablaVehiculos.clearSelection();
    }
    private void cbConductoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbConductoresActionPerformed

    }//GEN-LAST:event_cbConductoresActionPerformed

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void txtTipoMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoMotorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoMotorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarP;
    private javax.swing.JButton btnModificarPa1;
    private javax.swing.JButton btnRegistrarVehiculo;
    private javax.swing.JButton btn_eliminar_doctor1;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_photo;
    private javax.swing.JComboBox<String> cbConductores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaVehiculos;
    private javax.swing.JTextField txtIdentificacionC2;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtPotencia;
    private javax.swing.JTextField txtTipoMotor;
    // End of variables declaration//GEN-END:variables
}
